### ISSUE TITLE
静态资源的导入方式

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#666]

**Comment by luhc228** [comment]
### 在 CSS 文件中引入静态资源

相对路径：

```css
.container {
  background-image: url('@/assets/background.svg');
  background-image: url('../assets/background.svg');
}
```

url 引入：

```css
.container {
	background-image: url('https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg')
}
```

### 在 JSX 中引入静态资源

在 public 目录中有静态资源：

```jsx
return (
  <img src="/background.svg" />
  
  <div 
    style={{
      backgroundImage: 'url("/background.svg")',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center 110px',
      backgroundSize: '100%',
    }}
  />
)
```

url 引入：

```jsx
return (
  <img src="https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg" />
  
  <div 
    style={{
      backgroundImage: 'url("https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg")',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center 110px',
      backgroundSize: '100%',
    }}
  />
)
```

 import 的方式导入：

```jsx
import background from '@/assets/background.svg';

return (
  <img src={background} />
)
```

使用 @svgr/webpack：

```ts
export default defineConfig({
  webpack(webpackConfig) {
   	webpackConfig.module?.rules?.splice(7, 1, {
      test: /\.svg$/i,
      use: ['@svgr/webpack'],
    }); 
  }
})
```

```tsx
import Icon from '@assets/icon.svg';

export default () => <Icon />
```

> ssr 暂时不支持 @svgr/webpack
